### ISSUE TITLE
got a issue when execute "python okuna-cli.py up-services-only"

### ISSUE THREAD

**Issue by hungtooc** [OkunaOrg/okuna-api#710]
here is fully log:
\U0001f916 -> \u2b06  Bringing only the Okuna services up...
Creating network "okuna-api_okuna" with the default driver
Creating okuna-api_db_1    ... done
Creating okuna-api_redis_1 ... done
Creating okuna-worker      ... done
Creating okuna-scheduler   ... done
\U0001f916 -> Okuna was not bootstrapped.
\U0001f916 ->  Bootstrapping Okuna with some data
Traceback (most recent call last):
  File "okuna-cli.py", line 406, in <module>
    cli()
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "okuna-cli.py", line 330, in up_services_only
    _ensure_was_bootstrapped(is_local_api=True)
  File "okuna-cli.py", line 248, in _ensure_was_bootstrapped
    _bootstrap(is_local_api=is_local_api)
  File "okuna-cli.py", line 226, in _bootstrap
    subprocess.run(["./utils/scripts/bootstrap_development_data.sh"])
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hung5\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
\U0001f916 -> \u2b07  Bringing the Okuna services down...
Stopping okuna-api_redis_1 ... done
Stopping okuna-api_db_1    ... done
Removing okuna-worker      ... done
Removing okuna-scheduler   ... done
Removing okuna-api_redis_1 ... done
Removing okuna-api_db_1    ... done
Removing network okuna-api_okuna

**Comment by lifenautjoe** [comment]
Did you install the requirements before running this? pip install -r requirements.txt ? This looks like an error with the click package.

**Comment by hungtooc** [comment]
yes it was fixed by doing that way. thank you
