### ISSUE TITLE
Error 500 when changing the relationship between Post and PostImage to ForeignKey (from OneToOne)

### ISSUE THREAD

**Issue by alsiPanda** [OkunaOrg/okuna-api#736]
I am trying to make a multi image post, Most of which went well. Including the create post part with two images, which i checked in admin panel. But after that trying to view the posts in mobile sends an error 500, the logs are as follows: 

> 2020-10-16 03:28:04,782 django.request ERROR    Internal Server Error: /api/posts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/okuna-api/openbook_posts/views/posts/views.py", line 73, in get
    return self.get_posts_for_authenticated_user(request)
  File "/opt/okuna-api/openbook_posts/views/posts/views.py", line 128, in get_posts_for_authenticated_user
    post_serializer_data = AuthenticatedUserPostSerializer(posts, many=True, context={"request": request}).data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 757, in data
    ret = super().data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 261, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 675, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/cacheops/query.py", line 303, in _fetch_all
    return self._no_monkey._fetch_all(self)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1087, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 474, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 54, in pre_sql_setup
    self.setup_query()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 45, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 219, in get_select
    cols = self.get_default_columns()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 641, in get_default_columns
    only_load = self.deferred_to_columns()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1011, in deferred_to_columns
    self.query.deferred_to_data(columns, self.query.get_loaded_field_names_cb)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 717, in deferred_to_data
    callback(target, model, values)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1962, in get_loaded_field_names
_cb
    target[model] = {f.attname for f in fields}
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1962, in <setcomp>
    target[model] = {f.attname for f in fields}
AttributeError: 'ManyToOneRel' object has no attribute 'attname'

I tried searching through the files for `attname` but the only place was inside `VideoField` inside `video_encoding\fields.py`. I feel that should not be the right place to mess with. I have tried adding `'media'` to the response serializer for posts, but that doesn't seem to be the issue either. The two points of reference seem to be `return self.get_posts_for_authenticated_user(request)` and ` post_serializer_data = AuthenticatedUserPostSerializer(posts, many=True, context={"request": request}).data` but i cant seem to pinpoint the source of error.

Where do i look into to fix the error ? Thanks in advance.

Edit: After some more checking the problem seems to be limited to timeline posts. When I check profile, any profile, the feed there shows all the posts by the respective users. Narrowing further, the error only occurs in case of non-filtered post. As long as filter is applied the posts, there are no errors

**Comment by alsiPanda** [comment]
@evict , @javabudd  Any idea how to go about the above error ?

**Comment by alsiPanda** [comment]
Solved by removing `image` related things from the function `_get_timeline_posts_with_no_filters`
