### ISSUE TITLE
ImportError: cannot import name 'checksum' from 'modeltranslation.models' 

### ISSUE THREAD

**Issue by hungtooc** [OkunaOrg/okuna-api#749]
![image_2020_11_16T03_10_51_899Z](https://user-images.githubusercontent.com/24487114/99209440-c32e6300-27f5-11eb-9f74-68c2ba7e1d3c.png)

here is the installed module:
Package                          Version
-------------------------------- --------------------
appdirs                          1.4.4
APScheduler                      2.1.2
asgiref                          3.3.1
attrs                            19.3.0
Automat                          0.8.0
bandit                           1.5.1
beautifulsoup4                   4.9.3
blinker                          1.4
boto3                            1.16.0
botocore                         1.19.0
certifi                          2020.6.20
chardet                          3.0.4
click                            7.1.2
cloud-init                       20.3
colorama                         0.4.4
colorlog                         4.0.2
colormath                        3.0.0
command-not-found                0.3
configobj                        5.0.6
constantly                       15.1.0
coverage                         5.3
croniter                         0.3.35
cryptography                     2.8
cursor                           1.3.4
dbus-python                      1.2.16
decorator                        4.4.2
distro                           1.4.0
distro-info                      0.23ubuntu1
Django                           2.2.16
django-amazon-ses                4.0.0
django-appconf                   1.0.4
django-cacheops                  5.0.1
django-cursor-pagination         0.1.4
django-cuser                     2017.3.16
django-extensions                3.0.9
django-imagekit                  4.0.2
django-media-fixtures            0.0.3
django-model-utils               4.0.0
django-modeltranslation          0.16
django-nose                      1.4.7
django-ordered-model             3.4.1
django-positions                 0.6.0
django-proxy                     1.2.1
django-redis                     4.12.1
django-replicated                2.7
django-rq                        2.3.2
django-rq-scheduler              1.1.3
django-storages                  1.8
django-tinymce                   3.1.0
djangorestframework              3.12.1
dparse                           0.5.1
entrypoints                      0.3
Faker                            0.9.1
ffmpy                            0.2.3
filelock                         3.0.12
funcy                            1.15
gitdb                            4.0.5
GitPython                        3.1.9
halo                             0.0.30
httplib2                         0.14.0
hyperlink                        19.0.0
idna                             2.10
importlib-metadata               1.5.0
incremental                      16.10.1
Jinja2                           2.10.1
jmespath                         0.10.0
jsonpatch                        1.22
jsonpointer                      2.0
jsonschema                       3.2.0
keyring                          18.0.1
langdetect                       1.0.8
language-selector                0.1
launchpadlib                     1.10.13
lazr.restfulclient               0.14.2
lazr.uri                         1.0.3
log-symbols                      0.0.14
MarkupSafe                       1.1.0
mixer                            6.1.3
modeltranslation                 0.25
more-itertools                   4.2.0
mysqlclient                      2.0.1
natsort                          7.0.1
netifaces                        0.10.4
networkx                         2.5
nose                             1.3.7
nose-exclude                     0.5.0
numpy                            1.19.2
oauthlib                         3.1.0
onesignal-sdk                    1.1.0
packaging                        20.4
pathtools                        0.1.2
pbr                              5.5.1
pexpect                          4.6.0
pilkit                           2.0
Pillow                           8.0.0
pinocchio                        0.4.2
pip                              20.0.2
pyasn1                           0.4.2
pyasn1-modules                   0.2.1
PyGObject                        3.36.0
PyHamcrest                       1.9.0
PyJWT                            1.7.1
pymacaroons                      0.13.0
PyNaCl                           1.3.0
pyOpenSSL                        19.0.0
pyparsing                        2.4.7
pyrsistent                       0.15.5
pyserial                         3.4
python-apt                       2.0.0+ubuntu0.20.4.1
python-dateutil                  2.8.1
python-debian                    0.1.36ubuntu1
python-dotenv                    0.14.0
python-magic                     0.4.18
pytz                             2020.1
PyYAML                           5.3.1
redis                            3.5.3
requests                         2.24.0
requests-file                    1.5.1
requests-unixsocket              0.2.0
rest-framework-generic-relations 2.0.0
rq                               1.5.2
rq-scheduler                     0.10.0
s3transfer                       0.3.3
safety                           1.9.0
schedule                         0.6.0
SecretStorage                    2.3.1
sentry-sdk                       0.10.2
service-identity                 18.1.0
setuptools                       45.2.0
shutilwhich                      1.1.0
simplejson                       3.16.0
six                              1.15.0
smmap                            3.0.4
sos                              4.0
soupsieve                        2.0.1
spectra                          0.0.11
spinners                         0.0.24
sqlparse                         0.4.1
ssh-import-id                    5.10
stevedore                        3.2.2
systemd-python                   234
termcolor                        1.1.0
text-unidecode                   1.2
tldextract                       2.2.3
toml                             0.10.1
Twisted                          18.9.0
tzlocal                          2.1
ubuntu-advantage-tools           20.3
ufw                              0.36
unattended-upgrades              0.1
uritools                         3.0.0
url-normalize                    1.4.2
urlextract                       1.1.0
urllib3                          1.25.11
wadllib                          1.3.3
watchdog                         0.10.3
webpreview                       1.6.0
wheel                            0.34.2
zipp                             3.3.1
zope.interface                   4.7.1

**Comment by lindaAcc** [comment]
Same problem here : 
BASE_DIR /home/linda/Desktop/mametamorphose/wsway
ROOT_DIR /home/linda/Desktop/mametamorphose
MEDIA_ROOT /home/linda/Desktop/mametamorphose/media/
STATIC_ROOT /home/linda/Desktop/mametamorphose/static
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/linda/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/linda/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/linda/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/linda/.local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/linda/.local/lib/python3.8/site-packages/modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/linda/.local/lib/python3.8/site-packages/modeltranslation/models.py", line 75, in handle_translation_registrations
    autodiscover()
  File "/home/linda/.local/lib/python3.8/site-packages/modeltranslation/models.py", line 26, in autodiscover
    import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/linda/.local/lib/python3.8/site-packages/modeltranslation/translation.py", line 3, in <module>
    from modeltranslation.models import checksum, FieldTranslation, trans_attr, trans_is_fuzzy_attr
ImportError: cannot import name 'checksum' from 'modeltranslation.models' (/home/linda/.local/lib/python3.8/site-packages/modeltranslation/models.py)
